import 'package:flutter/material.dart';

final listChoiceColors = [
  Color(0xFFB18F67),
  Color(0xFF558687),
  Color(0xFF9D002B),
  Color(0xFF1C95A0),
  Color(0xFF949380),
  Color(0xFFCF9F35),
  Color(0xFF2B444C),
  Color(0xFF1C9B7F),
  Color(0xFFE78E2B),
  Color(0xFFBB221C),
  Color(0xFF148759),
  Color(0xFFDB4214),
  Color(0xFF1474B9),
  Color(0xFFFAFAFA),
  Color(0xFFBB8A7F),
  Color(0xFF9C2B78),
  Color(0xFF14579D),
  Color(0xFF141C22),
  Color(0xFF483D9A),
  Color(0xFFB18F67),
  Color(0xFF9FB6CD),
  Color(0xFF00CD00),
  Color(0xFF8B4513),
  Color(0xFF556B2F),
  Color(0xFF191970),
  Color(0xFF8B7500),
  Color(0xFF00688B),
];

var listColorCirclesContainer = [
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[0]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[1]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[2]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[3]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[4]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[5]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[6]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[7]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[8]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[9]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[10]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[11]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[12]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[13]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[14]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[15]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[16]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[17]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[18]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[19]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[20]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[21]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[22]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[23]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[24]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[25]),
  ),
  Container(
    margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
    width: 20.0,
    height: 20.0,
    child: Text(""),
    decoration: BoxDecoration(shape: BoxShape.circle, color: listChoiceColors[26]),
  ),
];
